name: The Stubborn Hakimi
favicon: null
layout_spectrum: 0.23492
typography_spectrum: 0.06036
title: Stubborn Hakimi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0c0a0b'
    - '#ebad3c'
    - '#b5110f'
    - '#b45b01'
  brandStrength: 0.0625
  lightness: 0.5864912495017052
  saturation: 0.9895118821877986
  rhythmicContrast: 0.25
purpose: []
