name: The Stubborn Hakimi
favicon: null
layout_spectrum: 0.23492
typography_spectrum: 0.10985952778719366
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5625
  lightness: 0.5864912495017052
  saturation: 0.9895118821877986
  rhythmicContrast: 0.25
purpose: []
