name: The Stubborn Hakimi
favicon: null
layout_spectrum: 0.9182
typography_spectrum: 0.06871
title: The Stubborn Hakimi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00011b'
    - '#ffffff'
    - '#fcb480'
    - '#95c0c1'
    - '#4b596f'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
