name: The Stubborn Hakimi
favicon: null
layout_spectrum: 0.9182
typography_spectrum: 0.06871
title: The Stubborn Hakimi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e1d8d1'
    - '#000000'
    - '#5a5268'
    - '#85828b'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
